server:
  port: 8080
spring:
  profiles:
    include: flyway
  application:
    name: orm-data
  datasource:
    url: jdbc:mysql://192.168.1.102:3306/test_db?setUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
